export enum ProjectDataTabs {
  Dashboard = 'dashboard',
  DataCosts = 'data-costs',
  Documents = 'documents',
}

export enum ProjectDataItemIds {
  PreparationOne = 1001,
  PreparationTwo,
  PreparationThree,
  PreparationFour,
  PreparationFive,
  BuildingOne = 2001,
  BuildingTwo,
  BuildingThree,
  BuildingFour,
  BuildingFive,
  BuildingSix,
  BuildingSeven,
  BuildingEight,
  BuildingNine,
  BuildingTen,
  BuildingEleven,
  BuildingTwelve,
  ExteriorEleven = 30011,
  ExteriorTwelve,
  ExteriorThirteen,
  ExteriorTwentyOne = 30021,
  ExteriorTwentyTwo,
  ExteriorTwentyThree,
  ExteriorThirtyOne = 30031,
  ExteriorThirtyTwo,
  ExteriorThirtyThree,
  ExteriorFortyOne = 30041,
  ExteriorFortyTwo,
  ExteriorFortyThree,
  TeamsThree = 4003,
  TeamsEleven = 40011,
  TeamsTwelve,
  TeamsThirteen,
  TeamsFourteen,
  TeamsFifteen,
  TeamsTwentyOne = 40021,
  TeamsTwentyTwo,
  TeamsTwentyThree,
  TeamsTwentyFour,
  SuppliersOne = 5001,
  SuppliersTwo,
  SuppliersThree,
  SuppliersFortyOne = 50041,
  SuppliersFortyTwo,
  SuppliersFortyThree,
  SuppliersFortyFour,
  SuppliersFortyFive,
  SuppliersFiftyOne = 50051,
  SuppliersFiftyTwo,
  SuppliersFiftyThree,
  SuppliersFiftyFour,
}